### ISSUE TITLE
типы данных для id

### ISSUE THREAD

**Issue by cucumberian** [egorantonov/gorzdrav#2]
Поправьте пожалуйста типы данных для эндпоинтов
- district id - строка
- lpu id - число
- specialty id - строка
- doctor id - строка
- appointment id - строка

Например есть врачи у которых в id русские буквы и точка: [https://gorzdrav.spb.ru/_api/api/v2/schedule/lpu/191/speciality/59/doctors](https://gorzdrav.spb.ru/_api/api/v2/schedule/lpu/191/speciality/59/doctors)

**Comment by egorantonov** [comment]
исправлено
